baseURL = 'https://manuj-mishra.github.io/'
languageCode = 'en-us'
title = 'Manuj Mishra'
theme = 'hermit'
pygmentsCodefences  = true
pygmentsUseClasses  = true
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
# googleAnalytics = "UA-123-45"

[author]
  name = "Manuj Mishra"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "02 Jan 2006"
  dateformShort   = "02 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 MST"
  # description = ""
  # images = [""]

  themeColor = "#494f5c"

  homeTitle = "Manuj Mishra"
  # homeSubtitle = "Machine Learning, Entrepreneurship, Science"
  # footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # bgImg = ""  # Homepage background-image URL

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = true  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields
  
  # Add custom css
  # customCSS = ["css/foo.css", "css/bar.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.

  [[params.social]]
    name = "github"
    url = "https://github.com/manuj-mishra"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/manuj-mishra/"
  
  [[params.social]]
    name = "email"
    url = "manujmishra2000@gmail.com"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "blog/"
    weight = 1
  
  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 2